name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Concatenation
      id: t1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Concatenation
        command: npm run test-1
        timeout: 1
        max-score: 1
    - name: Interpolation
      id: t2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Interpolation
        command: npm run test-2
        timeout: 1
        max-score: 1
    - name: Longueur de chaine
      id: t3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Longueur de chaine
        command: npm run test-3
        timeout: 1
        max-score: 1
    - name: Lettre à la position
      id: t4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lettre à la position
        command: npm run test-4
        timeout: 1
        max-score: 1
    - name: Dernier caractère
      id: t5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dernier caractère
        command: npm run test-5
        timeout: 1
        max-score: 1
    - name: Parler fort
      id: t6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Parler fort
        command: npm run test-6
        timeout: 1
        max-score: 1
    - name: Parler doucement
      id: t7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Parler doucement
        command: npm run test-7
        timeout: 1
        max-score: 1
    - name: Le texte contient
      id: t8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Le texte contient
        command: npm run test-8
        timeout: 1
        max-score: 1
    - name: Substituer du texte
      id: t9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Substituer du texte
        command: npm run test-9
        timeout: 1
        max-score: 1
    - name: Nettoyer un input
      id: t10
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Nettoyer un input
        command: npm run test-10
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1_RESULTS: "${{steps.t1.outputs.result}}"
        T2_RESULTS: "${{steps.t2.outputs.result}}"
        T3_RESULTS: "${{steps.t3.outputs.result}}"
        T4_RESULTS: "${{steps.t4.outputs.result}}"
        T5_RESULTS: "${{steps.t5.outputs.result}}"
        T6_RESULTS: "${{steps.t6.outputs.result}}"
        T7_RESULTS: "${{steps.t7.outputs.result}}"
        T8_RESULTS: "${{steps.t8.outputs.result}}"
      with:
        runners: t1,t2,t3,t4,t5,t6,t7,t8
