name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Test n°1 - Fichier index.html existe
      id: t1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Fichier index.html existe
        command: npm run test-1
        timeout: 1
        max-score: 1
    - name: Test n°2 - HTML bien formé
      id: t2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HTML bien formé
        command: npm run test-2
        timeout: 1
        max-score: 1
    - name: Test n°3 - Balise h1
      id: t3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Balise h1
        command: npm run test-3
        timeout: 1
        max-score: 1
    - name: Test n°4 - Balise h2
      id: t4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Balise h2
        command: npm run test-4
        timeout: 1
        max-score: 1
    - name: Test n°5 - Balises p
      id: t5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Balises p
        command: npm run test-5
        timeout: 1
        max-score: 1
    - name: Test n°6 - Balises br
      id: t6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Balises br
        command: npm run test-6
        timeout: 1
        max-score: 1
    - name: Test n°7 - Liste ordonnée ol
      id: t7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Liste ordonnée ol
        command: npm run test-7
        timeout: 1
        max-score: 1
    - name: Test n°8 - Liste non ordonnée ul
      id: t8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Liste non ordonnée ul
        command: npm run test-8
        timeout: 1
        max-score: 1
    - name: Test n°9 - Balises em
      id: t9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Balises em
        command: npm run test-9
        timeout: 1
        max-score: 1
    - name: Test n°10 - Balises strong
      id: t10
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Balises strong
        command: npm run test-10
        timeout: 1
        max-score: 1
    - name: Test n°11 - Éléments li bien imbriqués
      id: t11
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Éléments li bien imbriqués
        command: npm run test-11
        timeout: 1
        max-score: 1
    - name: Test n°12 - Contenu strong et em non vide
      id: t12
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Contenu strong et em non vide
        command: npm run test-12
        timeout: 1
        max-score: 1
    - name: Test n°13 - Structure logique h1 avant h2
      id: t13
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Structure logique h1 avant h2
        command: npm run test-13
        timeout: 1
        max-score: 1
    - name: Test n°14 - Pas de balises orphelines
      id: t14
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Pas de balises orphelines
        command: npm run test-14
        timeout: 1
        max-score: 1
    - name: Test n°15 - Body contient toutes les balises
      id: t15
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Body contient toutes les balises
        command: npm run test-15
        timeout: 1
        max-score: 1
    - name: Test n°16 - Contenu dans les balises
      id: t16
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Contenu dans les balises
        command: npm run test-16
        timeout: 1
        max-score: 1
    - name: Test n°17 - Langue du document fr (bonus)
      id: t17
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Langue du document fr
        command: npm run test-17
        timeout: 1
        max-score: 1
    - name: Test n°18 - Title modifié (bonus)
      id: t18
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Title modifié
        command: npm run test-18
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1_RESULTS: "${{steps.t1.outputs.result}}"
        T2_RESULTS: "${{steps.t2.outputs.result}}"
        T3_RESULTS: "${{steps.t3.outputs.result}}"
        T4_RESULTS: "${{steps.t4.outputs.result}}"
        T5_RESULTS: "${{steps.t5.outputs.result}}"
        T6_RESULTS: "${{steps.t6.outputs.result}}"
        T7_RESULTS: "${{steps.t7.outputs.result}}"
        T8_RESULTS: "${{steps.t8.outputs.result}}"
        T9_RESULTS: "${{steps.t9.outputs.result}}"
        T10_RESULTS: "${{steps.t10.outputs.result}}"
        T11_RESULTS: "${{steps.t11.outputs.result}}"
        T12_RESULTS: "${{steps.t12.outputs.result}}"
        T13_RESULTS: "${{steps.t13.outputs.result}}"
        T14_RESULTS: "${{steps.t14.outputs.result}}"
        T15_RESULTS: "${{steps.t15.outputs.result}}"
        T16_RESULTS: "${{steps.t16.outputs.result}}"
        T17_RESULTS: "${{steps.t17.outputs.result}}"
        T18_RESULTS: "${{steps.t18.outputs.result}}"
      with:
        runners: t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18
